version: "3.7"


networks:
  nwk-item-app:
    name: nwk-item-app

services:
  item-db:
    image: mongo
    restart: always
    networks:
    - nwk-item-app
    volumes:
    - app-db:/data/db
  item-app:
    # build: .
    image: item-app:v1
    ports:
    - "80:8080"
    networks:
    - nwk-item-app
    restart: always
    volumes:
    - app-data:/data/app

volumes:
  app-data:
  app-db: