version: "3.7"


networks:
  nwk-item-app:
    name: nwk-item-app

services:
  item-db:
    image: mongo:3
    restart: always
    networks:
    - nwk-item-app
    volumes:
    - app-db:/data/db
  item-app:
    # build: .
    image: hadezbladez/item-app:v1
    depends_on:
    - item-db
    ports:
    - "80:8080"
    networks:
    - nwk-item-app
    restart: always

volumes:
  app-db: